In [4]:
from Data import Data
from DataLoaderCustom import PatientDiffLoader

from torch.utils.data import DataLoader

In [5]:
full_dataset = PatientDiffLoader("./data/data.tsv")
loader = DataLoader(full_dataset, shuffle=True, batch_size=5)

In [6]:
for one, two, same in loader:
    print(one, two)
    break

Patient_39.Timepoint_6
Patient_01.Timepoint_3
Patient_23.Timepoint_5
Patient_26.Timepoint_2
Patient_52.Timepoint_7
tensor([[3318015000, 2876175000, 7754450000,  ...,         -1,         -1,
                 -1],
        [2864495000, 1523392500, 5175725000,  ...,         -1,         -1,
                 -1],
        [5615050000, 2470575000, 7948100000,  ...,         -1,         -1,
                 -1],
        [3451452500, 1716390000, 7130300000,  ...,         -1,         -1,
                 -1],
        [3896100000, 2198920000, 6660125000,  ...,         -1,         -1,
                 -1]]) tensor([[3318015000, 2876175000, 7754450000,  ...,         -1,         -1,
                 -1],
        [2864495000, 1523392500, 5175725000,  ...,         -1,         -1,
                 -1],
        [6635400000, 2866887500, 7152400000,  ...,         -1,         -1,
                 -1],
        [3451452500, 1716390000, 7130300000,  ...,         -1,         -1,
                 -1],
        [26

In [10]:
print(one)

print(two)

print(same)

tensor([[3318015000, 2876175000, 7754450000,  ...,         -1,         -1,
                 -1],
        [2864495000, 1523392500, 5175725000,  ...,         -1,         -1,
                 -1],
        [5615050000, 2470575000, 7948100000,  ...,         -1,         -1,
                 -1],
        [3451452500, 1716390000, 7130300000,  ...,         -1,         -1,
                 -1],
        [3896100000, 2198920000, 6660125000,  ...,         -1,         -1,
                 -1]])
tensor([[3318015000, 2876175000, 7754450000,  ...,         -1,         -1,
                 -1],
        [2864495000, 1523392500, 5175725000,  ...,         -1,         -1,
                 -1],
        [6635400000, 2866887500, 7152400000,  ...,         -1,         -1,
                 -1],
        [3451452500, 1716390000, 7130300000,  ...,         -1,         -1,
                 -1],
        [2619665000, 1307067500, 4487925000,  ...,         -1,         -1,
                 -1]])
tensor([[1.],
        [1.],
