In [1]:
from Data import Data
from DataLoaderCustom import PatientDiffLoader

from torch.utils.data import DataLoader

In [ ]:
full_dataset = PatientDiffLoader("./data/data.tsv", toLog = True) # getting log
loader = DataLoader(full_dataset, shuffle=True, batch_size=1)
for one, two, same in loader:
    print(one,"\n", two,"\n", same)
    break

In [2]:
full_dataset = PatientDiffLoader("./data/data.tsv", toBin = True) # getting binary
loader = DataLoader(full_dataset, shuffle=True, batch_size=1)
for one, two, same in loader:
    print(one,"\n", two,"\n", same)
    break

Patient_21.Timepoint_4
tensor([[ True,  True,  True,  ..., False, False, False]]) 
 tensor([[ True,  True,  True,  ..., False, False, False]]) 
 tensor([[0.]])


In [7]:
full_dataset.toBin = False #

for one, two, same in loader:
    print(one,"\n", two,"\n", same)
    break

Patient_36.Timepoint_4
tensor([[5745625000, 4006375000, 9916175000,  ...,          0,          0,
                  0]]) 
 tensor([[4893175000, 1332197500, 7174775000,  ...,          0,          0,
                  0]]) 
 tensor([[0.]])
